repos:
  - repo: local
    hooks:
      - id: glossary-alphabetical
        name: glossary-alphabetical
        entry: python scripts/glossary_alphabetical.py
        language: system
        files: 'glossary.qmd'
