project: 
  type: website
  preview:
    port: 4200
    browser: false
  
website: 
  page-navigation: true
  title: Cloud-Optimized Geospatial Formats Guide
  repo-url: https://github.com/developmentseed/cloud-optimized-geospatial-formats-guide
  repo-actions: [edit, issue]
  
  page-footer:
    right: "This page is built with ❤️ and [Quarto](https://quarto.org/)."
    left: "&copy; CC-By Openscapes, 2022"
    
  sidebar:
    pinned: true
    align: center
    tools: 
      - icon: github
        href: https://github.com/NASA-IMPACT/cloud-optimized-geospatial-formats-guide
        text: "Cloud-Optimized Geospatial Formats Guide"

    style: "docked"
    search: true
    collapse-level: 2
    contents:
      - href: index.qmd
        text: Welcome
      - href: overview.qmd
        text: Overview Slides    
      - section: Formats
        contents:
        - section: template.qmd
        - section: cloud-optimized-geotiffs.ipynb
          contents:
          - cogs-examples.ipynb
        - section: Zarr + Kerchunk
          contents:
          - text: Zarr + Kerchunk
        - section: Cloud-Optimized HDF5 + NetCDF
          contents:
          - text: Cloud-Optimized HDF5 + NetCDF
        - section: Cloud-Optimized Point Clouds (COPC)
          contents:
          - text: Cloud-Optimized Point Clouds (COPC)
        - section: GeoParquet
          contents:
          - text: GeoParquet
        - section: Flatgeobuf
          contents:
          - text: Flatgeobuf

format:
  html:
    theme:
      light: [cosmo, theme.scss] # from https://github.com/sta210-s22/website/blob/main/_quarto.yml
      dark: [cosmo, theme-dark.scss]
    code-copy: true
    code-overflow: wrap
    css: styles.css
    toc: true
    grid:
      sidebar-width: 350px


filters:
  - include-files.lua
  - quarto

  
