project:
  type: website
  preview:
    port: 4200
    browser: false

website:
  page-navigation: true
  title: Cloud-Optimized Geospatial Formats Guide
  repo-url: https://github.com/developmentseed/cloud-optimized-geospatial-formats-guide
  repo-actions: [edit, issue]

  page-footer:
    right: "This page is built with ❤️ and [Quarto](https://quarto.org/)."
    left: "&copy; CC-By [Development Seed](https://developmentseed.org), 2023"

  sidebar:
    pinned: true
    align: center
    tools:
      - icon: github
        href: https://github.com/developmentseed/cloud-optimized-geospatial-formats-guide
        text: "Cloud-Optimized Geospatial Formats Guide"

    style: "docked"
    search: true
    collapse-level: 2
    contents:
      - href: index.qmd
        text: Welcome
      - href: overview.qmd
        text: Overview Slides
      - section: Formats
        contents:
        - section: Cloud Optimized GeoTIFFs
          contents:
          - cloud-optimized-geotiffs/intro.ipynb
          - cloud-optimized-geotiffs/cogs-examples.ipynb
        - section: Zarr
          contents:
          - zarr/intro.qmd
          - zarr/zarr-in-practice.ipynb
        - section: Kerchunk
          contents:
          - kerchunk/intro.qmd
          - kerchunk/kerchunk-in-practice.ipynb
        - section: Cloud-Optimized HDF5 and NetCDF
          contents:
            - cloud-optimized-netcdf4-hdf5/index.qmd
        - section: Cloud-Optimized Point Clouds (COPC)
          contents:
            - copc/index.qmd
        - section: GeoParquet
          contents:
            - geoparquet/index.qmd
            - geoparquet/geoparquet-example.ipynb
        - section: FlatGeobuf
          contents:
            - flatgeobuf/intro.qmd
            - flatgeobuf/hilbert-r-tree.qmd
      - href: cookbooks/index.qmd
        text: Cookbooks
      - href: contributing.qmd
        text: Get Involved

format:
  html:
    theme:
      light: [cosmo, theme.scss] # from https://github.com/sta210-s22/website/blob/main/_quarto.yml
      dark: [cosmo, theme-dark.scss]
    code-copy: true
    code-overflow: wrap
    css: styles.css
    toc: true
    grid:
      sidebar-width: 400px


filters:
  - include-files.lua
  - quarto
